# app.py


import os
import gradio as gr
import joblib

# Load the trained model
deployed_dt = joblib.load("diabetes_prediction_model.pkl")


# Prediction Function
def predict_diabetes(
    pregnancies,
    glucose,
    blood_pressure,
    skin_thickness,
    insulin,
    bmi,
    diabetes_pedigree_function,
    age
):

    input_data = [[
        pregnancies,
        glucose,
        blood_pressure,
        skin_thickness,
        insulin,
        bmi,
        diabetes_pedigree_function,
        age
    ]]

    prediction = deployed_dt.predict(input_data)

    if prediction[0] == 1:
        return "⚠️ High Risk of Diabetes\n\nPlease consult a healthcare professional for further evaluation."
    else:
        return "✅ Low Risk of Diabetes\n\nMaintain a healthy lifestyle and regular health checkups."


# Gradio Interface
# Gradio Interface
interface = gr.Interface(
    fn=predict_diabetes,

    inputs=[
        gr.Slider(0, 17, value=1, step=1, label="👶 Pregnancies"),
        gr.Slider(0, 200, value=120, step=1, label="🩸 Glucose (mg/dL)"),
        gr.Slider(0, 130, value=70, step=1, label="💓 Blood Pressure (mm Hg)"),
        gr.Slider(0, 100, value=20, step=1, label="📏 Skin Thickness (mm)"),
        gr.Slider(0, 900, value=80, step=1, label="💉 Insulin (μU/ml)"),
        gr.Slider(0.0, 70.0, value=25.0, step=0.1, label="⚖️ BMI"),
        gr.Slider(0.05, 3.0, value=0.50, step=0.01, label="🧬 Diabetes Pedigree Function"),
        gr.Slider(18, 100, value=30, step=1, label="🎂 Age"),
    ],

    outputs=gr.Textbox(label="🩺 Prediction Result"),

    title="🩺 Diabetes Prediction System",

    description="""
# 🩺 Diabetes Prediction System

Welcome!

This application uses a **Decision Tree Machine Learning model** to estimate whether a patient is at **High Risk** or **Low Risk** of Diabetes based on medical parameters.

### 📋 Instructions
- Adjust all sliders according to the patient's medical data.
- Click **Submit**.
- The prediction will appear below.

> ⚠️ This prediction is for educational purposes and should not replace professional medical advice.
""",

    article="""
---

# 👩‍💻 Project Details

### Developed By
**Sneha Verma**

**Roll Number:** 28240091

**Department:** Computer Science & Engineering (CSE Core)

**College:** Panipat Institute of Engineering and Technology (PIET)

---

### 🔗 Connect with Me

**LinkedIn:**  
https://linkedin.com/in/sneha-verma-071b04322

---

### 🛠️ Technologies Used

- Python
- Gradio
- Scikit-Learn
- Decision Tree Classifier
- NumPy
- Joblib

---

### ⚠️ Disclaimer

This application is developed solely for **educational and demonstration purposes**.

The prediction generated by the machine learning model **does not constitute medical advice**. Always consult a qualified healthcare professional for diagnosis and treatment.
""",

    allow_flagging="never"
)

if __name__ == "__main__":
    interface.launch(
        server_name="0.0.0.0",
        server_port=int(os.environ.get("PORT", 7860))
    )
